INSERT INTO METHOD (NAME, DESCRIPTION, IMPLEMENTOR_CLASS, METHOD_TYPE_ID, MODULE_ID) VALUES ('changeCustomerUserPassword', 'Method for change user password', 'com.us.weavx.core.services.impl.UpdateCustomerUserPasswordMethodImpl', 3, 4);
INSERT INTO TOKEN_STATUS(ID, NAME, DESCRIPTION) VALUES (6, 'VALID', 'Valid token');

INSERT INTO PROPERTY(ID, NAME) VALUES (200, 'lang-new-password-container');
INSERT INTO PROPERTY(ID, NAME) VALUES (201, 'lang-pass1-otp_ph');
INSERT INTO PROPERTY(ID, NAME) VALUES (202, 'lang-pass2-otp_ph');
INSERT INTO PROPERTY(ID, NAME) VALUES (203, 'lang-password-strong');
INSERT INTO PROPERTY(ID, NAME) VALUES (204, 'lang-password-match');
INSERT INTO PROPERTY(ID, NAME) VALUES (205, 'lang-success-pass-change');
INSERT INTO PROPERTY(ID, NAME) VALUES (206, 'lang-success-pass-wait');



INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 200, 1, 'Ingresa tu nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 200, 2, 'Enter your new password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 200, 1, 'Ingresa tu nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 200, 2, 'Enter your new password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 200, 1, 'Ingresa tu nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 200, 2, 'Enter your new password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 200, 1, 'Ingresa tu nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 200, 2, 'Enter your new password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 200, 1, 'Ingresa tu nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 200, 2, 'Enter your new password');

INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 201, 1, 'Nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 201, 2, 'New password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 201, 1, 'Nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 201, 2, 'New password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 201, 1, 'Nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 201, 2, 'New password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 201, 1, 'Nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 201, 2, 'New password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 201, 1, 'Nueva contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 201, 2, 'New password');

INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 202, 1, 'Confirmar contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 202, 2, 'Confirm password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 202, 1, 'Confirmar contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 202, 2, 'Confirm password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 202, 1, 'Confirmar contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 202, 2, 'Confirm password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 202, 1, 'Confirmar contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 202, 2, 'Confirm password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 202, 1, 'Confirmar contraseña');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 202, 2, 'Confirm password');

INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 203, 1, 'El mínimo de caracteres debe ser 8 y debe contener al menos un número y una mayúscula');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 203, 2, 'The min length is 8 and must be at least one uppercase letter and one number');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 203, 1, 'El mínimo de caracteres debe ser 8 y debe contener al menos un número y una mayúscula');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 203, 2, 'The min length is 8 and must be at least one uppercase letter and one number');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 203, 1, 'El mínimo de caracteres debe ser 8 y debe contener al menos un número y una mayúscula');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 203, 2, 'The min length is 8 and must be at least one uppercase letter and one number');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 203, 1, 'El mínimo de caracteres debe ser 8 y debe contener al menos un número y una mayúscula');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 203, 2, 'The min length is 8 and must be at least one uppercase letter and one number');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 203, 1, 'El mínimo de caracteres debe ser 8 y debe contener al menos un número y una mayúscula');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 203, 2, 'The min length is 8 and must be at least one uppercase letter and one number');

INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 204, 1, 'Las contraseñas deben coincidir.');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 204, 2, 'The field must match with the password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 204, 1, 'Las contraseñas deben coincidir.');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 204, 2, 'The field must match with the password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 204, 1, 'Las contraseñas deben coincidir.');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 204, 2, 'The field must match with the password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 204, 1, 'Las contraseñas deben coincidir.');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 204, 2, 'The field must match with the password');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 204, 1, 'Las contraseñas deben coincidir.');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 204, 2, 'The field must match with the password');

INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 205, 1, 'Contraseña actualizada correctamente');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 205, 2, 'Password updated succesfully');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 205, 1, 'Contraseña actualizada correctamente');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 205, 2, 'Password updated succesfully');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 205, 1, 'Contraseña actualizada correctamente');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 205, 2, 'Password updated succesfully');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 205, 1, 'Contraseña actualizada correctamente');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 205, 2, 'Password updated succesfully');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 205, 1, 'Contraseña actualizada correctamente');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 205, 2, 'Password updated succesfully');

INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 206, 1, 'Espere un momento redirigiendo...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (54, 206, 2, 'Wait a moment redirecting...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 206, 1, 'Espere un momento redirigiendo...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (55, 206, 2, 'Wait a moment redirecting...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 206, 1, 'Espere un momento redirigiendo...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (56, 206, 2, 'Wait a moment redirecting...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 206, 1, 'Espere un momento redirigiendo...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (57, 206, 2, 'Wait a moment redirecting...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 206, 1, 'Espere un momento redirigiendo...');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (58, 206, 2, 'Wait a moment redirecting...');
