ALTER TABLE TRANSACTION 
	ADD COMMENTS VARCHAR;
ALTER TABLE TRANSACTION	
	ADD OPERATOR_ID BIGINT REFERENCES CUSTOMER_USER(ID) ON DELETE SET NULL;

ALTER TABLE TRANSACTION
	ADD OPERATOR_EMAIL VARCHAR;	
	
ALTER TABLE TRANSACTION_REPORT
	ADD CONTRIBUTION_DISCOUNT DECIMAL(10,2) DEFAULT 0.0;

ALTER TABLE TRANSACTION_REPORT
	ADD CONTRIBUTION_COMMISSION DECIMAL(10,2) DEFAULT 0.0;
	
ALTER TABLE TRANSACTION_REPORT
	ADD COMMENTS VARCHAR;
	
ALTER TABLE TRANSACTION_REPORT
	ADD OPERATOR_ID BIGINT;

ALTER TABLE TRANSACTION_REPORT
	ADD OPERATOR_EMAIL VARCHAR;

CREATE INDEX TRANSACTION_REPORT_OP_EMAIL_I1 ON TRANSACTION_REPORT(OPERATOR_EMAIL);

CREATE INDEX TRANSACTION_REPORT_OP_EMAIL_UPPER_I2 ON TRANSACTION_REPORT(UPPER(OPERATOR_EMAIL));