CREATE TABLE BLACKLIST_DATA_TYPE (
	ID 		INTEGER,
	NAME 	VARCHAR,
	VALID_REGEXP	VARCHAR,
	CONSTRAINT BLACKLIST_DATA_TYPE_PK PRIMARY KEY (ID),
	CONSTRAINT BLACKLIST_DATA_TYPE_NAME_UQ UNIQUE(NAME)
);

INSERT INTO BLACKLIST_DATA_TYPE (ID, NAME) VALUES (1, 'EMAIL');
INSERT INTO BLACKLIST_DATA_TYPE (ID, NAME) VALUES (2, 'IP');

CREATE TABLE BLACKLIST (
	ID	BIGSERIAL,
	BLOCKED_AT	timestamp without time zone default current_timestamp,
	DATA			VARCHAR not null,
	DATA_TYPE_ID		INTEGER not null,
	BLOCKED_BY		BIGINT,
	IS_ACTIVE		BOOLEAN DEFAULT true,
	CLEANED_AT	timestamp without time zone,
	CONSTRAINT BLACKLIST_PK PRIMARY KEY (ID),
	CONSTRAINT BLACKLIST_DATA_TYPE_FK FOREIGN KEY (DATA_TYPE_ID) REFERENCES BLACKLIST_DATA_TYPE (ID),
	CONSTRAINT BLACKLIST_DATA_UQ UNIQUE (DATA)
);

INSERT INTO BLACKLIST(DATA, DATA_TYPE_ID) VALUES ('admin@blacklist', 1);

CREATE INDEX BLACKLIST_I1 ON BLACKLIST(DATA_TYPE_ID, DATA);
INSERT INTO SYSTEM_PROPERTY(name, value, description) values ('BLACKLIST_MAX_DENIED_ATTEMPTS', '5', 'Cantidad de intentos de transacciones rechazadas antes de proceder al bloqueo en lista negra.');
INSERT INTO SYSTEM_PROPERTY(name, value, description) values ('BLACKLIST_ENABLED', 'true', 'Control de listas negras activado/desactivado.');

#CAMBIOS PARA INCORPORAR CARGA MASIVA
INSERT INTO METHOD (NAME, DESCRIPTION, IMPLEMENTOR_CLASS, METHOD_TYPE_ID, MODULE_ID) VALUES ('addAttendees', 'Method for add attendeees for an Event', 'com.us.weavx.core.services.impl.AddAttendeesMethodImpl', 3, 6);

#CAMBIOS PARA MEJORA DE LISTAS NEGRAS 20190506
INSERT INTO TRANSACTION_STATUS (ID, NAME) values (9, 'IN_BLACKLIST');
DROP INDEX BLACKLIST_I1;
CREATE INDEX BLACKLIST_I1 ON BLACKLIST(DATA_TYPE_ID, DATA, IS_ACTIVE);

