INSERT INTO SIGNATURE_GATEWAY (id, name, sandbox_url, production_url) VALUES (2, 'HARVESTFUL', 'http://172.31.52.167:8080/generatePDF/generatePDF/','http://172.31.52.167:8080/generatePDF/generatePDF/');
INSERT INTO METHOD (NAME, DESCRIPTION, IMPLEMENTOR_CLASS, METHOD_TYPE_ID, MODULE_ID) VALUES ('signUserEventContract','method for register new document signature', 'com.us.weavx.core.services.impl.SignUserEventContractMethodImpl',3,3);

INSERT INTO PROPERTY(ID, NAME) VALUES (215, 'clear-btn');
INSERT INTO PROPERTY(ID, NAME) VALUES (216, 'place-btn');
INSERT INTO PROPERTY(ID, NAME) VALUES (217, 'cancelBtn');
INSERT INTO PROPERTY(ID, NAME) VALUES (218, 'btn-agree-sign');
INSERT INTO PROPERTY(ID, NAME) VALUES (219, 'lang-download-contract');
INSERT INTO PROPERTY(ID, NAME) VALUES (220, 'lang-insert-signature');
INSERT INTO PROPERTY(ID, NAME) VALUES (221, 'success-signature-message');
INSERT INTO PROPERTY(ID, NAME) VALUES (222, 'lang-signature');
INSERT INTO PROPERTY(ID, NAME) VALUES (223, 'lang-upload-signature');

INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (215, 130, 1, 'Borrar');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (215, 130, 2, 'Clear');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (216, 130, 1, 'Seleccionar');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (216, 130, 2, 'Place');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (217, 130, 1, 'Cancelar');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (217, 130, 2, 'Cancel');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (218, 130, 1, 'Acepto');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (218, 130, 2, 'I Agree');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (219, 130, 1, 'Descargar Contrato');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (219, 130, 2, 'Download');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (220, 130, 1, 'Firme Aquí');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (220, 130, 2, 'Sign Here');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (221, 130, 1, 'Gracias por aceptar y firmar los términos de uso, presiona el botón para descargar una copia del contrato firmado. Hemos enviado a su correo electrónico el enlace para ingresar al evento.');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (221, 130, 2, 'Thank you for accepting and signing the terms of use, press the button to download a copy of the signed contract.');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (222, 130, 1, 'Escribe tu firma');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (222, 130, 2, 'Write your signature');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (223, 130, 1, 'Selecciona una imagen');
INSERT INTO CUSTOMER_PROPERTY_LANG(PROPERTY_ID, CUSTOMER_ID, LANG_ID, PROPERTY_VALUE) VALUES (223, 130, 2, 'Select an image');









