ALTER TABLE TRANSACTION
ADD IP_ADDRESS VARCHAR;
ALTER TABLE TRANSACTION
ADD USER_AGENT VARCHAR;

CREATE INDEX IP_TRANSACTION_INDEX ON TRANSACTION(IP_ADDRESS);
CREATE INDEX USERAGENT_TRANSACTION_INDEX ON TRANSACTION(USER_AGENT );

ALTER TABLE TRANSACTION_REPORT
ADD IP_ADDRESS VARCHAR;

ALTER TABLE TRANSACTION_REPORT
ADD USER_AGENT VARCHAR;


CREATE INDEX TRANSACTION_REPORT_IP_INDEX ON TRANSACTION_REPORT(IP_ADDRESS);
CREATE INDEX TRANSACTION_REPORT_UA_INDEX ON TRANSACTION_REPORT(USER_AGENT);


INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (207, 'EVENT_TAG_NAME', 'GP-SCR-26SEP20-ONL','GP-SCR-26SEP20-ONL');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (208, 'EVENT_TAG_NAME', 'GP-SDI-30SEP20-ONL','GP-SDI-30SEP20-ONL');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (209, 'EVENT_TAG_NAME', 'GP-SDI-03OCT20-ONL','GP-SDI-03OCT20-ONL');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (212, 'EVENT_TAG_NAME', 'GP-CTL-15SEP20-ONL','GP-CTL-15SEP20-ONL');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (213, 'EVENT_TAG_NAME', 'GP-CTL-18SEP20-ONL','GP-CTL-18SEP20-ONL');

INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (207, 'MAILCHIMP_KEY', '4c84719148c2f4461ef40309309026f0-us19','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (208, 'MAILCHIMP_KEY', '4c84719148c2f4461ef40309309026f0-us19','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (209, 'MAILCHIMP_KEY', '4c84719148c2f4461ef40309309026f0-us19','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (212, 'MAILCHIMP_KEY', '4c84719148c2f4461ef40309309026f0-us19','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (213, 'MAILCHIMP_KEY', '4c84719148c2f4461ef40309309026f0-us19','');

INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (207, 'MAILCHIMP_LIST_ID', 'ba88d7c94a','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (208, 'MAILCHIMP_LIST_ID', '8fa61370df','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (209, 'MAILCHIMP_LIST_ID', '8fa61370df','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (212, 'MAILCHIMP_LIST_ID', '8fa61370df','');
INSERT INTO APPLICATION_PARAMETER(APPLICATION_ID, NAME, VALUE, DESCRIPTION) VALUES (213, 'MAILCHIMP_LIST_ID', '8fa61370df','');

INSERT INTO SYSTEM_PROPERTY(ID, NAME, VALUE) VALUES (17, 'MAILCHIMP_ENDPOINT', 'https://mktapi.harvestful.org/mailchimp/');
INSERT INTO SYSTEM_PROPERTY(ID, NAME, VALUE) VALUES (18, 'MAILCHIMP_AUTH_TOKEN', '50aR7o/jc9khgBbzusuG7EehGkN4S6zqTBu538HNosfLcFufaMU4HxA2vA0Z2X4q9o+JpTeAYwJBAJtCq7vCQ+Wg6tmb14DrKWeuBmJyEJ9NuiUkj9L0TXNlYYbzl5K3EVSXZVDWZ4WFUmsJa0wgTsZLcoHYX/bM8kcCQF6SIMeCTJgOIrtgvfJMgaaJugeT6GV++BxBG5HT+iuLjs76e4PwiSAMbK7nTXVj2j6TiR3reRx/jyTQQjWHy6cCQAhR8lIFfw33KZ6vs0S9VWKw+Lad1jYzPB5xbyOm49+jNy68Lws1tEAMPOmwE6wcEOabgpx5vr7xnBlJNxtKsFECQDr1zlpxdnPYgwSYe0++HWuX2TDVkx79kV1WCqnw8ZkBmGboyP6QI1AF36jV0TK/ljYV19k/zbfNJaxWc13z3X4=');
INSERT INTO SYSTEM_PROPERTY(ID, NAME, VALUE) VALUES (19, 'MAILCHIMP_SERVER','us19');

INSERT INTO application(id, name, description, short_token_duration, long_token_duration, short_user_token_duration, long_user_token_duration, created_by, created_at, application_controller_class)
VALUES (205, 'PAYPAL_HARVESTFUL', 'Paypal Harvestful',15, 1440, 525600, 525600, 1, current_timestamp, 'com.us.weavx.core.application.impl.PayPerViewEventApplicationControllerImpl');


INSERT INTO METHOD (NAME, DESCRIPTION, IMPLEMENTOR_CLASS, METHOD_TYPE_ID, MODULE_ID) VALUES ('renewExpiredAccessToken','method for renew a expired access token', 'com.us.weavx.core.services.impl.RenewTokenMethodImpl',3,3);
INSERT INTO METHOD (NAME, DESCRIPTION, IMPLEMENTOR_CLASS, METHOD_TYPE_ID, MODULE_ID) VALUES ('findUsersEventInfo','method that returns registered and active clients to be seen in admin seminar', 'com.us.weavx.core.services.impl.FindUsersEventInfoMethodImpl',3,3);
INSERT INTO METHOD (NAME, DESCRIPTION, IMPLEMENTOR_CLASS, METHOD_TYPE_ID, MODULE_ID) VALUES ('addBlacklistItem','metodo que agrega un ip o correo a lista negra desde la aplicacion seminarioAdmin', 'com.us.weavx.core.services.impl.AddBlacklistItemMethodImpl',3,3);


CREATE INDEX TRANSACTION_USER_DATA_I1 ON TRANSACTION_USER_DATA(CUSTOMER_USER_ID);
CREATE INDEX TRANSACTION_I1 ON TRANSACTION(TX_USER_DATA_ID);
CREATE INDEX TRANSACTION_I2 ON TRANSACTION(TX_STATUS_ID);
