INSERT INTO CUSTOMER_SUPPORTED_EXTERNAL_PAYMENT_TYPE(CUSTOMER_ID, EXTERNAL_PT_ID) VALUES (35, 1);
INSERT INTO CUSTOMER_SUPPORTED_EXTERNAL_PAYMENT_TYPE(CUSTOMER_ID, EXTERNAL_PT_ID) VALUES (35, 2);
INSERT INTO CUSTOMER_SUPPORTED_EXTERNAL_PAYMENT_TYPE(CUSTOMER_ID, EXTERNAL_PT_ID) VALUES (35, 3);
INSERT INTO CUSTOMER_SUPPORTED_EXTERNAL_PAYMENT_TYPE(CUSTOMER_ID, EXTERNAL_PT_ID) VALUES (35, 4);

INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 31, 1, 'Cupón no válido.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 31, 2, 'Not valid coupon.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 32, 1, 'El cupón ya fue utilizado.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 32, 2, 'Coupon already used.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 33, 1, 'El cupón se encuentra vencido.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 33, 2, 'The coupon has expired.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 34, 1, 'El cupón no es válido para este Seminario.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 34, 2, 'Coupon not valid on this event');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 35, 1, 'Ha ocurrido un error. Intente más tarde.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 35, 2, 'An error occurred, please try again later.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 36, 1, 'Los correos no coinciden, verifíquelos nuevamente.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 36, 2, 'Los correos no coinciden, verifíquelos nuevamente.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 37, 1, 'Debe validar el cupón antes de hacer la reservación.');
INSERT INTO CUSTOMER_SYSTEM_MESSAGES_LANG (CUSTOMER_ID, SYSTEM_MESSAGE_ID, LANG_ID, MESSAGE) VALUES (35, 37, 2, 'Debe validar el cupón antes de hacer la reservación.');


INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 189, 1, 'Ingrese el cupón:');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 189, 2, 'Your coupon code:');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 190, 1, 'Validar');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 190, 2, 'Validate');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 191, 1, '¿Posees cupón?');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 191, 2, '¿Posees cupón?');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 192, 1, 'Información de la Tarjeta');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 192, 2, 'Información de la Tarjeta');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 193, 1, 'Descripción');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 193, 2, 'Descripción');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 194, 1, 'Total');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 194, 2, 'Total');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 195, 1, 'Descuento');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 195, 2, 'Descuento');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 196, 1, '/var/lib/templates/discount_row.html');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 196, 2, '/var/lib/templates/discount_row.html');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 197, 1, 'Limpiar');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 197, 2, 'Clean');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 198, 1, 'INCRÍBETE AQUÍ');
INSERT INTO CUSTOMER_PROPERTY_LANG(CUSTOMER_ID, PROPERTY_ID, LANG_ID, PROPERTY_VALUE) VALUES (35, 198, 1, 'SIGN UP HERE');

